local icons = {}

-- stylua: ignore
icons.diagnostics = {
   Error          = "",
   Warning        = "",
   Hint           = "",
   Info           = "",
}

-- stylua: ignore
icons.git = {
   Add            = "",
   Mod            = "",
   Remove         = "",
   Ignore         = "",
   Rename         = "",
   Untracked      = "U",
   Unmerged       = "",
   Staged         = "S",
   Unstaged       = "",
   Branch         = "",
}

-- stylua: ignore
icons.os = {
   Unix           = "", -- ebc6
   Mac            = "", -- e302
   Dos            = "", -- e70f
}

-- stylua: ignore
icons.fs = {
   DirClosed      = "",
   DirOpen        = "",
   DirEmptyClosed = "",
   DirEmptyOpen   = "",
   DirSymlink     = "",
   File           = "",
   FileSymlink    = "",
   Exec           = "",
   Unknown        = "",
}

-- stylua: ignore
icons.kind = {
   File           = "",
   Module         = "",
   Namespace      = " ",
   Package        = "",
   Class          = "",
   Method         = "",
   Field          = "ﰠ",
   Constructor    = "",
   Enum           = "練",
   Interface      = "",
   Function       = "",
   Variable       = "",
   Constant       = "",
   String         = "",
   Text           = "",
   Number         = "",
   Boolean        = "",
   Array          = "",
   Object         = "",
   Key            = "",
   Keyword        = "",
   Null           = " ",
   EnumMember     = "練",
   Struct         = "",
   Property       = "",
   Event          = "",
   Operator       = "",
   TypeParameter  = "",
   Unit           = "",
   Value          = "",
   Snippet        = "",
   Color          = "",
   Reference      = "",
   Folder         = "",
}

-- stylua: ignore
icons.custom = {
   Octoface       = "",
   Emoji          = "ﲃ",
   Crates         = "",
}

-- stylua: ignore
icons.type = {
   Array          = "",
   Number         = "",
   String         = "",
   Boolean        = "蘒",
   Object         = "",
}

icons.misc = {}

return icons

-- if vim.fn.has "mac" == 1 or vim.g.use_nerd_icons then
--    -- elseif vim.fn.has "mac" == 1 then
--    return {
--      kind = {
--        Text = "",
--        -- Method = "m",
--        -- Function = "",
--        -- Constructor = "",
--        Method = "",
--        Function = "",
--        Constructor = "",
--        Field = "",
--        -- Variable = "",
--        Variable = "",
--        Class = "",
--        Interface = "",
--        -- Module = "",
--        Module = "",
--        Property = "",
--        Unit = "",
--        Value = "",
--        Enum = "",
--        -- Keyword = "",
--        Keyword = "",
--        -- Snippet = "",
--        Snippet = "",
--        Color = "",
--        File = "",
--        Reference = "",
--        Folder = "",
--        EnumMember = "",
--        Constant = "",
--        Struct = "",
--        Event = "",
--        Operator = "",
--        TypeParameter = "",
--      },
--      type = {
--        Array = "",
--        Number = "",
--        String = "",
--        Boolean = "蘒",
--        Object = "",
--      },
--      documents = {
--        File = "",
--        Files = "",
--        Folder = "",
--        OpenFolder = "",
--      },
--      git = {
--        Add = "",
--        Mod = "",
--        Remove = "",
--        Ignore = "",
--        Rename = "",
--        Diff = "",
--        Repo = "",
--        Octoface = "",
--      },
--      ui = {
--        ArrowClosed = "",
--        ArrowOpen = "",
--        Lock = "",
--        Circle = "",
--        BigCircle = "",
--        BigUnfilledCircle = "",
--        Close = "",
--        NewFile = "",
--        Search = "",
--        Lightbulb = "",
--        Project = "",
--        Dashboard = "",
--        History = "",
--        Comment = "",
--        Bug = "",
--        Code = "",
--        Telescope = "",
--        Gear = "",
--        Package = "",
--        List = "",
--        SignIn = "",
--        SignOut = "",
--        Check = "",
--        Fire = "",
--        Note = "",
--        BookMark = "",
--        Pencil = "",
--        -- ChevronRight = "",
--        ChevronRight = ">",
--        Table = "",
--        Calendar = "",
--        CloudDownload = "",
--      },
--      diagnostics = {
--        Error = "",
--        Warning = "",
--        Information = "",
--        Question = "",
--        Hint = "",
--      },
--      misc = {
--        Robot = "ﮧ",
--        Squirrel = "",
--        Tag = "",
--        Watch = "",
--        Smiley = "ﲃ",
--        Package = "",
--        CircuitBoard = "",
--      },
--    }
--  else
--    --   פּ ﯟ   蘒練 some other good icons
--    return {
--      kind = {
--        Text = " ",
--        Method = " ",
--        Function = " ",
--        Constructor = " ",
--        Field = " ",
--        Variable = " ",
--        Class = " ",
--        Interface = " ",
--        Module = " ",
--        Property = " ",
--        Unit = " ",
--        Value = " ",
--        Enum = " ",
--        Keyword = " ",
--        Snippet = " ",
--        Color = " ",
--        File = " ",
--        Reference = " ",
--        Folder = " ",
--        EnumMember = " ",
--        Constant = " ",
--        Struct = " ",
--        Event = " ",
--        Operator = " ",
--        TypeParameter = " ",
--        Misc = " ",
--      },
--      type = {
--        Array = " ",
--        Number = " ",
--        String = " ",
--        Boolean = " ",
--        Object = " ",
--      },
--      documents = {
--        File = " ",
--        Files = " ",
--        Folder = " ",
--        OpenFolder = " ",
--      },
--      git = {
--        Add = " ",
--        Mod = " ",
--        Remove = " ",
--        Ignore = " ",
--        Rename = " ",
--        Diff = " ",
--        Repo = " ",
--        Octoface = " ",
--      },
--      ui = {
--        ArrowClosed = "",
--        ArrowOpen = "",
--        Lock = " ",
--        Circle = " ",
--        BigCircle = " ",
--        BigUnfilledCircle = " ",
--        Close = " ",
--        NewFile = " ",
--        Search = " ",
--        Lightbulb = " ",
--        Project = " ",
--        Dashboard = " ",
--        History = " ",
--        Comment = " ",
--        Bug = " ",
--        Code = " ",
--        Telescope = " ",
--        Gear = " ",
--        Package = " ",
--        List = " ",
--        SignIn = " ",
--        SignOut = " ",
--        NoteBook = " ",
--        Check = " ",
--        Fire = " ",
--        Note = " ",
--        BookMark = " ",
--        Pencil = " ",
--        ChevronRight = "",
--        Table = " ",
--        Calendar = " ",
--        CloudDownload = " ",
--      },
--      diagnostics = {
--        Error = " ",
--        Warning = " ",
--        Information = " ",
--        Question = " ",
--        Hint = " ",
--      },
--      misc = {
--        Robot = " ",
--        Squirrel = " ",
--        Tag = " ",
--        Watch = " ",
--        Smiley = " ",
--        Package = " ",
--        CircuitBoard = " ",
--      },
-- }
--  end
