version: "3.9" 

services:
   machine:
      build: .
      container_name: nvim-config
      image: nvim-config:machine
      init: true
      ports:
         - 8080:3000
      volumes:
         - .:/root/.config/nvim
      stdin_open: true
      tty: true
      command: /bin/bash
