version: "3"
services:
   machine:
      container_name: nvim-config-V2
      build: .
      stdin_open: true
      tty: true
      command: /bin/bash
      ports:
         - 8080:3000
      volumes:
         - .:/root/.config/nvim
